config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboards#hello'

  get 'dashboards/report'

  resources :appointments

  resources :diagnostics

  resources :time_slots

  resources :physicians

  resources :patients

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:time_name, :time, :taken)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_name %><br>
    <%= f.text_field :time_name %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :taken %><br>
    <%= f.check_box :taken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time_slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<h1>Listing time_slots</h1>

<table>
  <thead>
    <tr>
      <th>Time name</th>
      <th>Time</th>
      <th>Taken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.time_name %></td>
        <td><%= time_slot.time %></td>
        <td><%= time_slot.taken %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time name:</strong>
  <%= @time_slot.time_name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @time_slot.time %>
</p>

<p>
  <strong>Taken:</strong>
  <%= @time_slot.taken %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>